"""Data layer for Saaf Bir — portable across SQLite (local) and Postgres (hosted).

Backend selection (single env var):
  * DATABASE_URL set and starting with postgres:// or postgresql:// -> Postgres
    (via psycopg 3). Use this for durable managed hosting (Neon / Supabase free tier).
  * Otherwise -> local SQLite, zero config. The DB file lives next to the package
    by default (override with SAAF_DB).

Routes stay backend-agnostic: they always call `get_conn()` and use `?`
placeholders, `conn.execute(...).fetchone()/.fetchall()`, `dict(row)`,
`cur.lastrowid`, and `conn.commit()`. A thin wrapper below makes both backends
behave the same:
  * `?` placeholders are rewritten to `%s` for Postgres.
  * INSERTs transparently get `RETURNING id` on Postgres so `lastrowid` works.
  * rows are always dict-accessible (`row["col"]`) and `dict(row)`-able.

Photos are stored in a column named `photo` — BLOB on SQLite, BYTEA on Postgres.
"""
import os
import re
import sqlite3
from pathlib import Path

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
IS_PG = DATABASE_URL.startswith(("postgres://", "postgresql://"))

DB_PATH = Path(os.environ.get("SAAF_DB", Path(__file__).resolve().parent.parent / "saaf.db"))

# --- Schema -----------------------------------------------------------------
# Two dialects, same logical schema. Both idempotent (IF NOT EXISTS).
# Differences: AUTOINCREMENT vs GENERATED IDENTITY, BLOB vs BYTEA,
# datetime('now') vs now(), REAL vs DOUBLE PRECISION.

_SCHEMA_SQLITE = """
CREATE TABLE IF NOT EXISTS households (
    id              TEXT PRIMARY KEY,
    village         TEXT,
    ward            TEXT,
    name            TEXT,
    phone           TEXT,
    type            TEXT,
    monthly_fee     REAL,
    prev_balance    REAL,
    service_months  INTEGER,
    fee_paid        REAL,
    current_balance REAL
);

CREATE TABLE IF NOT EXISTS household_months (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    household_id  TEXT REFERENCES households(id),
    month         TEXT,
    status        TEXT,
    txn_date      TEXT,
    receipt_no    TEXT,
    amount        REAL
);
CREATE INDEX IF NOT EXISTS idx_hm_house ON household_months(household_id);
CREATE INDEX IF NOT EXISTS idx_hm_month ON household_months(month);

CREATE TABLE IF NOT EXISTS reports (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    kind        TEXT NOT NULL,
    spot_type   TEXT,
    lat         REAL,
    lng         REAL,
    note        TEXT,
    photo       BLOB,
    photo_mime  TEXT,
    source      TEXT DEFAULT 'resident',
    created_at  TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS pickups (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    household_id  TEXT,
    action        TEXT NOT NULL,
    reason        TEXT,
    amount        REAL,
    created_at    TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS camps (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    focus_area  TEXT,
    date        TEXT,
    attendees   INTEGER,
    runner      TEXT,
    outcome     TEXT,
    created_at  TEXT DEFAULT (datetime('now'))
);
"""

_SCHEMA_PG = """
CREATE TABLE IF NOT EXISTS households (
    id              TEXT PRIMARY KEY,
    village         TEXT,
    ward            TEXT,
    name            TEXT,
    phone           TEXT,
    type            TEXT,
    monthly_fee     DOUBLE PRECISION,
    prev_balance    DOUBLE PRECISION,
    service_months  INTEGER,
    fee_paid        DOUBLE PRECISION,
    current_balance DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS household_months (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id  TEXT REFERENCES households(id),
    month         TEXT,
    status        TEXT,
    txn_date      TEXT,
    receipt_no    TEXT,
    amount        DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_hm_house ON household_months(household_id);
CREATE INDEX IF NOT EXISTS idx_hm_month ON household_months(month);

CREATE TABLE IF NOT EXISTS reports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        TEXT NOT NULL,
    spot_type   TEXT,
    lat         DOUBLE PRECISION,
    lng         DOUBLE PRECISION,
    note        TEXT,
    photo       BYTEA,
    photo_mime  TEXT,
    source      TEXT DEFAULT 'resident',
    created_at  TEXT DEFAULT (now()::text)
);

CREATE TABLE IF NOT EXISTS pickups (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id  TEXT,
    action        TEXT NOT NULL,
    reason        TEXT,
    amount        DOUBLE PRECISION,
    created_at    TEXT DEFAULT (now()::text)
);

CREATE TABLE IF NOT EXISTS camps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    focus_area  TEXT,
    date        TEXT,
    attendees   INTEGER,
    runner      TEXT,
    outcome     TEXT,
    created_at  TEXT DEFAULT (now()::text)
);
"""

SCHEMA = _SCHEMA_PG if IS_PG else _SCHEMA_SQLITE

# Tables the app exports / introspects (used by the export route's CSV path).
TABLE_COLUMNS = {
    "households": ["id", "village", "ward", "name", "phone", "type", "monthly_fee",
                   "prev_balance", "service_months", "fee_paid", "current_balance"],
    "household_months": ["id", "household_id", "month", "status", "txn_date",
                         "receipt_no", "amount"],
    "reports": ["id", "kind", "spot_type", "lat", "lng", "note", "photo",
                "photo_mime", "source", "created_at"],
    "pickups": ["id", "household_id", "action", "reason", "amount", "created_at"],
    "camps": ["id", "focus_area", "date", "attendees", "runner", "outcome",
              "created_at"],
}


# --- Postgres adapter -------------------------------------------------------

_INSERT_RE = re.compile(r"^\s*INSERT\s", re.IGNORECASE)
_RETURNING_RE = re.compile(r"\bRETURNING\b", re.IGNORECASE)


def _to_pg(sql: str) -> str:
    """Rewrite SQLite-style `?` placeholders to psycopg `%s`.

    `%` literals would confuse psycopg's client-side formatting, so escape any
    bare `%` (e.g. in LIKE patterns) before swapping placeholders.
    """
    sql = sql.replace("%", "%%")
    return sql.replace("?", "%s")


class _PGCursor:
    """Wraps a psycopg cursor to mimic the sqlite3 cursor surface used by routes."""

    def __init__(self, cur):
        self._cur = cur
        self.lastrowid = None

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()


class _PGConn:
    """sqlite3.Connection-compatible wrapper over a psycopg connection."""

    def __init__(self, conn):
        self._conn = conn

    def execute(self, sql: str, params=()):
        from psycopg.rows import dict_row

        pg_sql = _to_pg(sql)
        want_id = bool(_INSERT_RE.match(sql)) and not _RETURNING_RE.search(sql)
        if want_id:
            pg_sql = pg_sql.rstrip().rstrip(";") + " RETURNING id"
        cur = self._conn.cursor(row_factory=dict_row)
        cur.execute(pg_sql, tuple(params))
        wrapped = _PGCursor(cur)
        if want_id:
            row = cur.fetchone()
            wrapped.lastrowid = row["id"] if row else None
        return wrapped

    def executescript(self, script: str):
        # psycopg can run multiple statements in one execute() call.
        self._conn.execute(script)
        return self

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        # Match the original sqlite usage: commit on clean exit, rollback on error.
        if exc_type is None:
            self._conn.commit()
        else:
            self._conn.rollback()
        self._conn.close()
        return False


# --- Public API -------------------------------------------------------------

def get_conn():
    """Return a connection. SQLite by default; Postgres when DATABASE_URL is set.

    Both expose: execute(sql, params)->cursor, executescript(sql), commit(),
    context-manager support, dict-accessible rows, and cursor.lastrowid.
    """
    if IS_PG:
        import psycopg

        raw = psycopg.connect(DATABASE_URL)
        return _PGConn(raw)

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_db() -> None:
    """Create the schema on the active backend (idempotent)."""
    with get_conn() as conn:
        conn.executescript(SCHEMA)
        conn.commit()
